### ISSUE TITLE
Velocity log initialization error

### ISSUE THREAD

**Issue by marcoglur** [marcoglur/hdugen#2]
Sometimes the error occurs during test-execution: `Failed to initialize an instance of org.apache.velocity.runtime.log.CommonsLogLogChute with the current runtime configuration.`

**Comment by marcoglur** [comment]
Stack trace

	Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.CommonsLogLogChute with the current runtime configuration.
	org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.CommonsLogLogChute with the current runtime configuration.
		at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:875)
		at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:262)
		at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:646)
		at org.apache.velocity.runtime.RuntimeSingleton.init(RuntimeSingleton.java:226)
		at org.apache.velocity.app.Velocity.init(Velocity.java:97)
		at org.hdugen.scenario.VelocityScenario.xml(VelocityScenario.scala:23)
		at org.hdugen.scenario.Scenario$class.apply(Scenario.scala:13)
		at org.hdugen.scenario.VelocityScenario.apply(VelocityScenario.scala:17)
		at org.hdugen.core.Core$$anonfun$1$$anonfun$2.apply(Core.scala:55)
		at org.hdugen.core.Core$$anonfun$1$$anonfun$2.apply(Core.scala:55)
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
		at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
		at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
		at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
		at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
		at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	Caused by: org.apache.velocity.exception.VelocityException: Failed to initialize an instance of org.apache.velocity.runtime.log.CommonsLogLogChute with the current runtime configuration.
		at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:220)
		at org.apache.velocity.runtime.log.LogManager.updateLog(LogManager.java:269)
		at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:871)
		... 16 more
	Caused by: org.apache.velocity.exception.VelocityException: The specified logger class org.apache.velocity.runtime.log.CommonsLogLogChute does not implement the org.apache.velocity.runtime.log.LogChute interface.
		at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:181)
		... 18 more
